# These are supported funding model platforms

github: [ikarago]
patreon: ikarago
open_collective: # Replace with a single Open Collective username
ko_fi: ikarago
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://paypal.me/ikarago
